# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QvS2vpPpK9PTF81ySRXdSIPFH5FpNHFP
"""

class Calculator:
    def add(x, y):

        return x + y

    def subtract(x, y):

        return x - y

    def multiply(x, y):

        return x * y

    def divide(x, y):

        if y == 0:
            return "Error! Division by zero."
        else:
            return x / y

# Create an instance of the Calculator class

# Example usage:
  op = input ("enter the operation: ")
  a = op[1]
  if a== "+"
    x=Calculator.add(int (op[1]),int(op[2]))
    print("result: ")str

print("a + b =", Calculator.add(a, b))
print("a - b =", Calculator.subtract(a, b))
print("a * b =", Calculator.multiply(4, 6))
print("a / b =", Calculator.divide(10, 2))

class Calculator:
    @staticmethod
    def add(x, y):
        return x + y

    @staticmethod
    def sub(x, y):
        return x - y

    @staticmethod
    def mul(x, y):
        return x * y

    @staticmethod
    def div(x, y):
        if y != 0:
            return x / y
        else:
            return "Cannot be divided by zero"

operation = input("Enter the operation in the format 'number1 operator number2' (e.g., 1 + 2): ")

# Split the operation string into operands and operator
operands = operation.split()
x = float(operands[0])
y = float(operands[2])
op = operands[1]

result = None
if op == '+':
    result = Calculator.add(x, y)
elif op == '-':
    result = Calculator.sub(x, y)
elif op == '*':
    result = Calculator.mul(x, y)
elif op == '/':
    result = Calculator.div(x, y)
else:
    print("Invalid operator")

if result is not None:
    print(f"The result of {operation} is {result}")